--- 
clone: 
  depth: 1
kind: pipeline
name: Blaster4385AOSPPipeline
steps: 
  - 
    environment:
      TZ: Asia/Dubai
      TG_TOKEN: 
        from_secret: TOKEN
      CHANNEL_ID:
        from_secret: CHATID
    commands:
      - "ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone"
      - "apt update"
      - "apt -y install curl wget"
      - "apt -y install git"
      - "apt install zip unzip"
      - "apt -y install python2-minimal"
      - "apt -y install python3"
      - "ln -s /usr/bin/python2.7 /usr/bin/python"
      - "mkdir ~/bin"
      - "PATH=~/bin:$PATH"
      - "curl https://storage.googleapis.com/git-repo-downloads/repo > ~/bin/repo"
      - "chmod a+x ~/bin/repo"
      - "git config --global color.ui false"
      - "curl https://raw.githubusercontent.com/Blaster4385/scripts/main/setup.sh | bash"
      - "curl https://raw.githubusercontent.com/Blaster4385/scripts/main/build_aosp | bash"
    image: ubuntu:latest
    name: Build
    trigger: 
      branch: 
        - master
